services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: php_web
    volumes:
      - ./web:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - postgres_db


  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=library
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  postgres_data: